name: Christopher Kollars
description: Front-End Developer
highlighter: pygments
url: http://christopherkollars.com
imgSrc: /img
author:
  name: Christopher Kollars
  email: chris@christopherkollars.com

exclude: ["gulpfile.js", "node_modules", "package.json"]

include: ['.htaccess']

future: true
show_drafts: true


