# Site settings
title: Christopher Kollars
description: Front-End Developer
baseurl: ""
url: "http://christopherkollars.com"
author: Christopher Kollars

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  sass_dir: assets/scss

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - README.md
  - CNAME
  - node_modules
  - assets/scss

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
